### ISSUE TITLE
Transition fade out-in doesn't work as expected on first load

### ISSUE THREAD

**Issue by clingor** [FranckFreiburger/http-vue-loader#6]
**HTML Markup**
`<transition name="fade" mode="out-in">
    <component :is="selectedModule"></component>
</transition>`

**Components Load**
`Vue.component('component-a', httpVueLoader.load('app/components/component-a.vue', 'component-a'));
Vue.component('component-b', httpVueLoader.load('app/components/component-b.vue', 'component-b'));
Vue.component('component-c', httpVueLoader.load('app/components/component-c.vue', 'component-c'));`

It appears the _out-in_ transition behaves the same as the _in-out_ transition (Component B fades in before/during Component A fade out), but only on the first load of the component.  If switching between previously loaded (cached?) components, transitions behave as expected.  Please see the attached GIF demonstrating the behavior.

I've been digging into the source in hopes to address this myself through a pull request, but unfortunately I'm very new to Vue and some of this is still a mystery to me.  If there's anything else I can provide, I'm happy to do so.  Thanks!

**Demo GIF**
![vuetransitionerror_20170524](https://cloud.githubusercontent.com/assets/6201067/26434297/a152ca7c-40cd-11e7-8528-4c9ff92e6bf0.gif)

**Comment by FranckFreiburger** [comment]
Have you already tested this behavior without using http-vue-loader ?

**Comment by clingor** [comment]
Yes, sorry I didn't demonstrate this in the GIF.  When I include an inline component in the HTML (not loaded by http-vue-loader), that component will transition as expected on the first render.  This works as expected side-by-side with components loaded by http-vue-loader.

`<script>
	Vue.component('greeting', {
		template: '<h1>Hello World!</h1>'
	});
</script>`

If it would help, I can mock up a sample project and attach the zip file later tonight.

**Comment by FranckFreiburger** [comment]
The issue is related to the async components loading, I can obtain the same behavior without http-vue-loader (look at this example: https://jsfiddle.net/z11fe07p/1959/).
Currently I just asked about this behavior on the forum (https://forum.vuejs.org/t/out-in-transition-with-async-components/11654)

**Comment by clingor** [comment]
Thank you for looking into this!  I'm glad to see you're able to reproduce the behavior.  I'll follow your post on the Vue forums.  Thanks again!

**Comment by FranckFreiburger** [comment]
FYI, https://github.com/vuejs/vue/issues/5760

**Comment by clingor** [comment]
That's great news, thanks for logging the bug!

**Comment by FranckFreiburger** [comment]
fixed in vuejs v2.3.4

**Comment by clingor** [comment]
Thanks again for giving this issue attention.  Unfortunately, after pulling the latest version it still appears the bug persists.  Please see the GitHub repo below for an example demonstrating the issue.

[Vue Async Component Bug](https://github.com/clingor/githubIssuesFileShare/tree/master/vue-async-component-bug)

Perhaps the issue lies in my code somewhere, or maybe in the transition css?

**Comment by FranckFreiburger** [comment]
Sorry, the fix is not public yet, wait for v2.3.5 ?

**Comment by clingor** [comment]
That might be useful for visibility in case somebody else runs into this issue and needs to know the minimum version that fixed it.

**Comment by FranckFreiburger** [comment]
fixed in vue.js public release v2.4.0 Kill la Kill

> fix out-in transition for async components (#5760) (c3cdfcf)

**Comment by clingor** [comment]
I agree if you want to close this issue since it is out of your hands at this point, but it does appear the issue still exists in Vue 2.4.2.  Just commenting for your awareness in case this appears again.

[Async Component Transition Bug Demo](https://github.com/clingor/githubIssuesFileShare/tree/master/vue-async-component-bug)

**Comment by FranckFreiburger** [comment]
https://github.com/vuejs/vue/issues/5760#issuecomment-317672083

**Comment by FranckFreiburger** [comment]
fixed (see https://github.com/vuejs/vue/issues/6256)
